import streamlit as st
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from datetime import datetime

# Page Configuration
st.set_page_config(page_title="MAYA AI - Advanced Predictor", layout="wide")

st.title("MAYA AI: Shift-Wise Pattern Predictor")
st.markdown("Yeh system historical lag aur statistical patterns ko combine karke numbers (00-99) predict karne ki koshish karta hai.")

# --- Independent Date Selection for Shifts ---
st.sidebar.header("Data Selection Controls")

st.sidebar.subheader("Base Shift Settings")
base_start_date = st.sidebar.date_input("Base Shift Start Date", datetime(2023, 1, 1))
base_end_date = st.sidebar.date_input("Base Shift End Date", datetime(2026, 4, 1))

st.sidebar.subheader("Other Shifts Settings")
other_start_date = st.sidebar.date_input("Other Shifts Start Date", datetime(2023, 1, 1))
other_end_date = st.sidebar.date_input("Other Shifts End Date", datetime(2026, 4, 1))

# --- Dummy Data Generator (Aap yahan apna Excel file upload logic laga sakte hain) ---
def load_and_prep_data():
    # Creating a sample dataset (00-99)
    dates = pd.date_range(start='2023-01-01', end='2026-04-01')
    data = pd.DataFrame({
        'Date': dates,
        'Base_Shift_Num': np.random.randint(0, 100, size=len(dates)),
        'Other_Shift_Num': np.random.randint(0, 100, size=len(dates))
    })
    return data

df = load_and_prep_data()

# Filtering Data based on independent date selections
base_data = df[(df['Date'].dt.date >= base_start_date) & (df['Date'].dt.date <= base_end_date)][['Date', 'Base_Shift_Num']]
other_data = df[(df['Date'].dt.date >= other_start_date) & (df['Date'].dt.date <= other_end_date)][['Date', 'Other_Shift_Num']]

# --- Feature Engineering (Mixing Different Patterns) ---
def create_features(data, col_name):
    """
    Yeh function pichle dinon ke patterns (Lags) aur moving averages banata hai.
    Yeh un sabhi logic ka mixture hai jo historical trends ko pakadte hain.
    """
    df_feat = data.copy()
    # Pattern 1: Pichle 1, 2, aur 3 din ke numbers (Lag Features)
    for i in range(1, 4):
        df_feat[f'Lag_{i}'] = df_feat[col_name].shift(i)
    
    # Pattern 2: Pichle 3 aur 7 din ka average trend (Moving Average)
    df_feat['Rolling_Mean_3'] = df_feat[col_name].rolling(window=3).mean()
    df_feat['Rolling_Mean_7'] = df_feat[col_name].rolling(window=7).mean()
    
    # Drop empty rows generated by lag/rolling
    df_feat = df_feat.dropna()
    return df_feat

st.write("### Data Processing Status")
with st.spinner("Analyzing patterns and extracting features..."):
    base_features = create_features(base_data, 'Base_Shift_Num')
    
# --- Machine Learning Model (Random Forest) ---
if not base_features.empty:
    # Defining X (Patterns) and y (Target Number to guess)
    X = base_features.drop(['Date', 'Base_Shift_Num'], axis=1)
    y = base_features['Base_Shift_Num']
    
    # Splitting data for training
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Training the Model
    model = RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42)
    model.fit(X_train, y_train)
    
    st.success("Model Training Complete! All patterns mixed successfully.")
    
    # Prediction for the next shift
    # Taking the last known data point to predict the future
    latest_data = X.iloc[-1].values.reshape(1, -1)
    prediction = model.predict(latest_data)
    
    # Display Results
    st.markdown("---")
    st.write("### Predicted Outcome")
    st.metric(label="Next Base Shift Expected Number", value=int(round(prediction[0])))
    
    st.info("Note: Random Forest pichle patterns ka weighted average leta hai. LSTM add karne ke liye hum iske output ko deep learning pipeline me bhej sakte hain.")
else:
    st.warning("Data kafi nahi hai. Kripya date range badhayein.")

